# Generated by Django 3.2.3 on 2021-06-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter enemy name/title', max_length=50)),
                ('level', models.IntegerField(help_text='Enter enemy Level')),
                ('bio', models.TextField(help_text='Enter enemy biography')),
                ('HP', models.IntegerField()),
                ('EXP', models.IntegerField()),
                ('STR', models.IntegerField()),
                ('DEF', models.IntegerField()),
                ('ATS', models.IntegerField()),
                ('ADF', models.IntegerField()),
                ('SPD', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemDrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of item', max_length=50)),
                ('drop_chance', models.FloatField(help_text='Enter drop chance as decimal')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Locations with enemies', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('desc', models.TextField(help_text='Description of art or ability', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnbalanceEfficacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slash', models.IntegerField(choices=[('1/5', 1), ('2/5', 2), ('3/5', 3), ('4/5', 4), ('5/5', 5)], default=1)),
                ('thrust', models.IntegerField(choices=[('1/5', 1), ('2/5', 2), ('3/5', 3), ('4/5', 4), ('5/5', 5)], default=1)),
                ('pierce', models.IntegerField(choices=[('1/5', 1), ('2/5', 2), ('3/5', 3), ('4/5', 4), ('5/5', 5)], default=1)),
                ('strike', models.IntegerField(choices=[('1/5', 1), ('2/5', 2), ('3/5', 3), ('4/5', 4), ('5/5', 5)], default=1)),
                ('enemy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tocs_database.enemy')),
            ],
        ),
        migrations.CreateModel(
            name='StatusEfficacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poision', models.IntegerField(default=100)),
                ('seal', models.IntegerField(default=100)),
                ('mute', models.IntegerField(default=100)),
                ('blind', models.IntegerField(default=100)),
                ('sleep', models.IntegerField(default=100)),
                ('burn', models.IntegerField(default=100)),
                ('freeze', models.IntegerField(default=100)),
                ('petrify', models.IntegerField(default=100)),
                ('faint', models.IntegerField(default=100)),
                ('confuse', models.IntegerField(default=100)),
                ('deathblow', models.IntegerField(default=100)),
                ('nightmare', models.IntegerField(default=100)),
                ('at_delay', models.IntegerField(default=100)),
                ('vanish', models.IntegerField(default=100)),
                ('s_down', models.IntegerField(default=100)),
                ('enemy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tocs_database.enemy')),
            ],
        ),
        migrations.CreateModel(
            name='SepithDropped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earth', models.IntegerField(blank=True, null=True)),
                ('water', models.IntegerField(blank=True, null=True)),
                ('fire', models.IntegerField(blank=True, null=True)),
                ('wind', models.IntegerField(blank=True, null=True)),
                ('Time', models.IntegerField(blank=True, null=True)),
                ('space', models.IntegerField(blank=True, null=True)),
                ('mirage', models.IntegerField(blank=True, null=True)),
                ('mass', models.IntegerField(blank=True, null=True)),
                ('enemy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tocs_database.enemy')),
            ],
        ),
        migrations.AddField(
            model_name='enemy',
            name='item',
            field=models.ManyToManyField(help_text='Item Drops for enemy', to='tocs_database.ItemDrops'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tocs_database.location'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='skills',
            field=models.ManyToManyField(help_text='Enemy skills', to='tocs_database.Skills'),
        ),
        migrations.CreateModel(
            name='ElementalEfficacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earth', models.IntegerField()),
                ('water', models.IntegerField()),
                ('fire', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('Time', models.IntegerField(blank=True, null=True)),
                ('space', models.IntegerField(blank=True, null=True)),
                ('mirage', models.IntegerField(blank=True, null=True)),
                ('enemy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tocs_database.enemy')),
            ],
        ),
    ]
