# Generated by Django 3.2.3 on 2021-06-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocs_database', '0003_auto_20210622_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemDrops',
            new_name='ItemDrop',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameField(
            model_name='enemy',
            old_name='poision_efficacy',
            new_name='poison_efficacy',
        ),
        migrations.AlterField(
            model_name='enemy',
            name='earth_sepith',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='fire_sepith',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='mass_sepith',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='mirage_sepith',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='space_sepith',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='time_sepith',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='water_sepith',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='wind_sepith',
            field=models.IntegerField(default=0),
        ),
    ]
