# Generated by Django 3.2.3 on 2021-06-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tocs_database', '0004_auto_20210622_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='Time_efficacy',
            new_name='time_efficacy',
        ),
    ]
