# Generated by Django 3.2.3 on 2021-06-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocs_database', '0005_rename_time_efficacy_enemy_time_efficacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='ability_type',
            field=models.CharField(choices=[('Art', 'A'), ('Craft', 'C')], default='A', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='desc',
            field=models.TextField(help_text='Description of art or ability', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
