# Generated by Django 3.2.3 on 2021-06-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tocs_database', '0007_auto_20210622_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='items',
            field=models.ForeignKey(help_text='Item Drops for enemy', on_delete=django.db.models.deletion.PROTECT, to='tocs_database.itemdrop'),
        ),
    ]
