# Generated by Django 3.2.3 on 2021-06-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocs_database', '0009_auto_20210622_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='pierce',
            field=models.CharField(choices=[('1/5', '1'), ('2/5', '2'), ('3/5', '3'), ('4/5', '4'), ('5/5', '5')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='slash',
            field=models.CharField(choices=[('1/5', '1'), ('2/5', '2'), ('3/5', '3'), ('4/5', '4'), ('5/5', '5')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='strike',
            field=models.CharField(choices=[('1/5', '1'), ('2/5', '2'), ('3/5', '3'), ('4/5', '4'), ('5/5', '5')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='thrust',
            field=models.CharField(choices=[('1/5', '1'), ('2/5', '2'), ('3/5', '3'), ('4/5', '4'), ('5/5', '5')], default='1', max_length=10),
        ),
    ]
