# Generated by Django 3.2.3 on 2021-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocs_database', '0011_enemy_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
