# Generated by Django 3.2.3 on 2021-06-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocs_database', '0013_alter_enemy_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
