# Generated by Django 3.2.3 on 2021-07-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocs_database', '0016_alter_enemy_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='ability_type',
            field=models.CharField(blank=True, choices=[('Art', 'A'), ('Craft', 'C')], max_length=20),
        ),
    ]
