# Generated by Django 3.2.3 on 2021-07-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocs_database', '0017_alter_skill_ability_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='boss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enemy',
            name='boss_notes',
            field=models.TextField(blank=True, help_text='Enter notes or advice on fight.', max_length=2000),
        ),
    ]
