# Generated by Django 3.2.3 on 2021-07-13 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tocs_database', '0018_auto_20210713_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='dates',
            field=models.DateField(default=django.utils.timezone.now, help_text='Enter Ingame date(s) that player visits Location'),
            preserve_default=False,
        ),
    ]
