# Generated by Django 3.2.3 on 2021-07-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocs_database', '0020_alter_location_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='dates',
            field=models.DateField(help_text='Enter First Ingame date(s) that player visits Location'),
        ),
    ]
