# Generated by Django 3.2.3 on 2021-07-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocs_database', '0023_enemy_spoiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='high_elements',
            field=models.BooleanField(default=False),
        ),
    ]
