# Generated by Django 3.2.3 on 2021-07-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocs_database', '0024_location_high_elements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Locations with enemies', max_length=50, unique=True),
        ),
    ]
